{
 "title": "PFSense",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "NetInterface",
    "label": "Network Interface",
    "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> group(columns:[\"_measurement\"])\n  |> unique(column:\"friendlyname\")\n  |> keep(columns:[\"friendlyname\",\"name\",\"ip4_address\",\"ip6_address\"])\n  "
   },
   {
    "name": "WAN_GW",
    "label": "WAN Gateway",
    "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\n  |> filter(fn: (r) => r[\"_field\"] == \"defaultgw\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> unique(column:\"interface\")\n  |> group(columns:[\"interface\", \"gateway_name\"])\n  |> group()\n  |> keep(columns:[\"gateway_name\",\"interface\"])"
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_users\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\n  |> filter(fn: (r) => r[\"cpu\"] != \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Process Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blocked\" or r[\"_field\"] == \"idle\" or r[\"_field\"] == \"running\" or r[\"_field\"] == \"sleeping\" or r[\"_field\"] == \"zombies\" or r[\"_field\"] == \"wait\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load15\" or r[\"_field\"] == \"load5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PF Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pf\")\n  |> filter(fn: (r) => r[\"_field\"] == \"match\" or r[\"_field\"] == \"state-insert\" or r[\"_field\"] == \"state-mismatch\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" or r[\"_measurement\"] == \"swap\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"degrees\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "pfBlocker Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "IP - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> group()\n  |> top(n: 10)\n  |> drop(columns:[\"_start\",\"_stop\"])"
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)\n  |> drop(columns:[\"_start\",\"_stop\"])"
    }
   ]
  },
  {
   "title": "IP - Blocked Packet Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> rename(columns: {\"_value\": \"Blocked Inbound\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> rename(columns: {\"_value\": \"Blocked Outbound\"})\n\n  |> group()"
    }
   ]
  },
  {
   "title": "IP  - Src/Dst Blocked Geo",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ip_evaluated\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"geoip_code\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "DNSBL - Blocked Domain Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\n  |> group(columns: [\"tld\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> group()\n  "
    }
   ]
  },
  {
   "title": " DNSBL - Source IP - Top 10 Blocked",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\n  |> group(columns: [\"tld\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\"], mode:\"by\")\n  |> count(column: \"_value\")\n  |> sort(columns: [\"_value\"], desc: true)\n  |> group()\n  |> top(n: 10)\n  |> drop(columns:[\"_start\",\"_stop\"])"
    }
   ]
  },
  {
   "title": "Top 10 DNSBL  Blocked Domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"tld\"], mode:\"by\")\n  |> sort(columns: [\"_value\"], desc: true)\n  |> count()\n  |> group()\n  |> top(n: 10)\n\n  "
    }
   ]
  },
  { "title": "pfBlocker Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "IP - Top 10 Blocked - IN (by Host/Port)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\", \"dest_ip\",\"dest_port\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "Port - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"dest_port\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "Top 10 DNSBL Feeds",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 23 },
   "targets": [
    {
     "query": "  from(bucket:\"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_dnsbl_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blocktype\")\n  |> group(columns: [\"feed_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)\n  |> drop(columns: [\"_start\",\"_stop\"])"
    }
   ]
  },
  {
   "title": "Port - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"dest_port\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT (by Host/Port)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\", \"dest_ip\",\"dest_port\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - IN (by Host/Protocol)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\", \"dest_ip\",\"protocol\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "Protocol - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"in\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"protocol\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "Top 10 IP Block Feeds",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 30 },
   "targets": [
    {
     "query": " from(bucket:\"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"action\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"feed_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)\n  |> drop(columns: [\"_start\",\"_stop\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Protocol - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"protocol\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT (by Host/Protocol)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail_ip_block_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"direction\")\n  |> filter(fn: (r) => r[\"_value\"] == \"out\")\n  |> group(columns: [\"src_ip\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"src_ip\", \"dest_ip\",\"protocol\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> top(n: 10)"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Gateway RTT - ${WAN_GW}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\n  |> filter(fn: (r) => r[\"_field\"] == \"delay\")\n  |> filter(fn: (r) => r[\"gateway_name\"] =~ /^${WAN_GW:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Interface Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: -1m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"friendlyname\"])\n  |> last()\n  |> group()\n  |> drop(columns: [\"_field\",\"_time\",\"source\",\"_start\",\"_stop\",\"_measurement\",\"host\", \"ip4_subnet\",\"ip6_subnet\"])"
    }
   ]
  },
  {
   "title": "Gateway Loss - ${WAN_GW}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\n  |> filter(fn: (r) => r[\"_field\"] == \"loss\")\n  |> filter(fn: (r) => r[\"gateway_name\"] =~ /^${WAN_GW:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GATEWAY SUMMARY - ${WAN_GW}",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 46 },
   "targets": [
    {
     "query": "intInfo = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: -1m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> rename(columns: {ip4_address: \"ipaddress\", name: \"interface\"})\n\n\ngwInfo = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: -1m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gateways\")\n |> filter(fn: (r) => r[\"_field\"] == \"source\" or r[\"_field\"] == \"status\" or  r[\"_field\"] == \"gwdescr\" or r[\"_field\"] == \"monitor\" or r[\"_field\"] == \"defaultgw\" or r[\"_field\"] == \"substatus\")\n  |> filter(fn: (r) => r[\"gateway_name\"] =~ /${WAN_GW:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\"])\n  |> rename(columns: {source: \"ipaddress\"})\n\n\n   \njoin(\n    tables: {gwInfo: gwInfo, intInfo: intInfo},\n    on: [\"interface\"],\n)\n  |> group(columns: [\"gateway_name\"])\n\n  |> last(column: \"friendlyname\")\n  |> group()\n  |> keep(columns: [\"gwdescr\",\"interface\",\"ipaddress_gwInfo\",\"monitor\",\"name\",\"status\", \"defaultgw\", \"substatus\"])"
    }
   ]
  },
  { "title": "${NetInterface}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }, "repeat": "NetInterface" },
  {
   "title": "Interface Summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"${dataSource}\")\n  |> range(start: -1m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"friendlyname\"] == \"${NetInterface}\")\n  |> keep(columns:[\"name\",\"friendlyname\",\"ip4_address\",\"ip6_address\",\"mac_address\"])\n  |> unique(column: \"friendlyname\")\n  |> group(columns:[\"interface\"])"
    }
   ]
  },
  {
   "title": "${NetInterface} Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "intInfo =   from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"friendlyname\"] == \"${NetInterface}\")\n  |> distinct(column: \"friendlyname\")\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"interface\"})\n\n\nnetStats = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  \n\n \njoin(\n    tables: {netStats: netStats, intInfo: intInfo},\n    on: [\"interface\"],\n)"
    }
   ]
  },
  {
   "title": "${NetInterface} Traffic - bits per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "intInfo =   from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"friendlyname\"] == \"${NetInterface}\")\n  |> distinct(column: \"friendlyname\")\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"interface\"})\n\n\nnetStats = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  \n\n \njoin(\n    tables: {netStats: netStats, intInfo: intInfo},\n    on: [\"interface\"],\n)"
    }
   ]
  },
  {
   "title": "${NetInterface} - Monthly",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "intInfo =   from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"friendlyname\"] == \"${NetInterface}\")\n  |> distinct(column: \"friendlyname\")\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"interface\"})\n\n\nnetStats = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: -30d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\n  |> derivative(unit: 30d, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: 1d, fn: mean)\n  \n\n \njoin(\n    tables: {netStats: netStats, intInfo: intInfo},\n    on: [\"interface\"],\n)"
    }
   ]
  },
  {
   "title": "${NetInterface} Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "intInfo =   from(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\n  |> filter(fn: (r) => r[\"friendlyname\"] == \"${NetInterface}\")\n  |> distinct(column: \"friendlyname\")\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"interface\"})\n\n\nnetStats = \nfrom(bucket: \"${dataSource}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  \n\n \njoin(\n    tables: {netStats: netStats, intInfo: intInfo},\n    on: [\"interface\"],\n)"
    }
   ]
  }
 ]
}